export interface ProductMixData {
  name: string;
  category: string;
  qtySold: number;
  grossSales: number;
  discount: number;
  netSales: number;
  voids: number;
  comps: number;
  dayPart: string;
}

export const productMixData: ProductMixData[] = [
  // Main Course - Breakfast
  {
    name: "Margherita Pizza",
    category: "Main Course",
    qtySold: 245,
    grossSales: 3920,
    discount: 196.0,
    netSales: 3724.0,
    voids: 3,
    comps: 1,
    dayPart: "Breakfast",
  },
  {
    name: "Ribeye Steak",
    category: "Main Course",
    qtySold: 142,
    grossSales: 6616,
    discount: 340.8,
    netSales: 6275.2,
    voids: 1,
    comps: 1,
    dayPart: "Breakfast",
  },
  {
    name: "Grilled Salmon",
    category: "Main Course",
    qtySold: 156,
    grossSales: 4992,
    discount: 0.0,
    netSales: 4992.0,
    voids: 0,
    comps: 2,
    dayPart: "Breakfast",
  },

  // Appetizer - Breakfast
  {
    name: "Caesar Salad",
    category: "Appetizer",
    qtySold: 198,
    grossSales: 2376,
    discount: 118.8,
    netSales: 2257.2,
    voids: 1,
    comps: 0,
    dayPart: "Breakfast",
  },
  {
    name: "Tomato Soup",
    category: "Appetizer",
    qtySold: 120,
    grossSales: 1800,
    discount: 90.0,
    netSales: 1710.0,
    voids: 2,
    comps: 0,
    dayPart: "Breakfast",
  },
  {
    name: "Bruschetta",
    category: "Appetizer",
    qtySold: 75,
    grossSales: 1125,
    discount: 56.25,
    netSales: 1068.75,
    voids: 0,
    comps: 0,
    dayPart: "Breakfast",
  },

  // Main Course - Lunch
  {
    name: "Grilled Salmon",
    category: "Main Course",
    qtySold: 150,
    grossSales: 6000,
    discount: 100.0,
    netSales: 5900.0,
    voids: 0,
    comps: 0,
    dayPart: "Lunch",
  },
  {
    name: "Pasta Carbonara",
    category: "Main Course",
    qtySold: 134,
    grossSales: 2948,
    discount: 147.4,
    netSales: 2800.6,
    voids: 0,
    comps: 1,
    dayPart: "Lunch",
  },
  {
    name: "Ribeye Steak",
    category: "Main Course",
    qtySold: 142,
    grossSales: 6816,
    discount: 340.8,
    netSales: 6475.2,
    voids: 1,
    comps: 0,
    dayPart: "Lunch",
  },

  // Dessert - Lunch
  {
    name: "Chocolate Cake",
    category: "Dessert",
    qtySold: 95,
    grossSales: 950,
    discount: 47.5,
    netSales: 902.5,
    voids: 0,
    comps: 0,
    dayPart: "Lunch",
  },
  {
    name: "Tiramisu",
    category: "Dessert",
    qtySold: 82,
    grossSales: 820,
    discount: 41.0,
    netSales: 779.0,
    voids: 1,
    comps: 0,
    dayPart: "Lunch",
  },
  {
    name: "Cheesecake",
    category: "Dessert",
    qtySold: 63,
    grossSales: 945,
    discount: 47.25,
    netSales: 897.75,
    voids: 1,
    comps: 0,
    dayPart: "Lunch",
  },

  // Main Course - Dinner
  {
    name: "Margherita Pizza",
    category: "Main Course",
    qtySold: 245,
    grossSales: 3920,
    discount: 196.0,
    netSales: 3724.0,
    voids: 3,
    comps: 1,
    dayPart: "Dinner",
  },
  {
    name: "Pasta Carbonara",
    category: "Main Course",
    qtySold: 134,
    grossSales: 2948,
    discount: 147.4,
    netSales: 2800.6,
    voids: 0,
    comps: 0,
    dayPart: "Dinner",
  },
  {
    name: "Ribeye Steak",
    category: "Main Course",
    qtySold: 142,
    grossSales: 6616,
    discount: 340.8,
    netSales: 6275.2,
    voids: 1,
    comps: 0,
    dayPart: "Dinner",
  },

  // Appetizer - Dinner
  {
    name: "Caesar Salad",
    category: "Appetizer",
    qtySold: 198,
    grossSales: 2376,
    discount: 118.8,
    netSales: 2257.2,
    voids: 1,
    comps: 0,
    dayPart: "Dinner",
  },
  {
    name: "Tomato Soup",
    category: "Appetizer",
    qtySold: 120,
    grossSales: 1800,
    discount: 90.0,
    netSales: 1710.0,
    voids: 2,
    comps: 0,
    dayPart: "Dinner",
  },
  {
    name: "Bruschetta",
    category: "Appetizer",
    qtySold: 75,
    grossSales: 1125,
    discount: 56.25,
    netSales: 1068.75,
    voids: 0,
    comps: 0,
    dayPart: "Dinner",
  },

  // Dessert - Dinner
  {
    name: "Chocolate Cake",
    category: "Dessert",
    qtySold: 95,
    grossSales: 950,
    discount: 47.5,
    netSales: 902.5,
    voids: 0,
    comps: 0,
    dayPart: "Dinner",
  },
  {
    name: "Tiramisu",
    category: "Dessert",
    qtySold: 82,
    grossSales: 820,
    discount: 41.0,
    netSales: 779.0,
    voids: 1,
    comps: 0,
    dayPart: "Dinner",
  },
  {
    name: "Cheesecake",
    category: "Dessert",
    qtySold: 63,
    grossSales: 945,
    discount: 47.25,
    netSales: 897.75,
    voids: 1,
    comps: 0,
    dayPart: "Dinner",
  },
];
